import { randomUUID } from 'crypto';
import { getDatabase } from '../db/database.js';

export interface EmbedData {
  title: string;
  content: string;
  styles?: string;
}

export interface EmbedResult {
  tokenId: string;
  token: string;
  embedCode: string;
  expiresAt: string;
}

export function generateEmbedToken(): string {
  return randomUUID().replace(/-/g, '');
}

export function createEmbedHtml(data: EmbedData): string {
  const defaultStyles = `
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      margin: 0;
      padding: 24px;
      color: #333;
      background: #fff;
      line-height: 1.6;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 2px solid #3498db;
      padding-bottom: 8px;
      margin-bottom: 16px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
    }
    th {
      background: #2c3e50;
      color: #fff;
      padding: 10px 12px;
      text-align: left;
      font-weight: 600;
    }
    td {
      padding: 8px 12px;
      border-bottom: 1px solid #e0e0e0;
    }
    tr:nth-child(even) {
      background: #f5f5f5;
    }
    .chart-placeholder {
      background: #f8f9fa;
      border: 2px dashed #ccc;
      padding: 40px;
      text-align: center;
      color: #888;
      border-radius: 8px;
      margin: 16px 0;
    }
    .footer {
      margin-top: 24px;
      padding-top: 12px;
      border-top: 1px solid #eee;
      font-size: 12px;
      color: #999;
    }
  `;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(data.title)}</title>
  <style>${data.styles || defaultStyles}</style>
</head>
<body>
  <h1>${escapeHtml(data.title)}</h1>
  ${data.content}
  <div class="footer">Generated by Ivy Agent Export</div>
</body>
</html>`;
}

export function storeEmbedToken(
  exportId: string,
  data: EmbedData,
  expiresInHours: number = 72
): EmbedResult {
  const db = getDatabase();
  const tokenId = randomUUID();
  const token = generateEmbedToken();
  const htmlContent = createEmbedHtml(data);

  const expiresAt = new Date(Date.now() + expiresInHours * 60 * 60 * 1000).toISOString();
  const createdAt = new Date().toISOString();

  db.prepare(`
    INSERT INTO embed_tokens (id, export_id, token, html_content, expires_at, created_at)
    VALUES (?, ?, ?, ?, ?, ?)
  `).run(tokenId, exportId, token, htmlContent, expiresAt, createdAt);

  const embedCode = `<iframe src="embed://${token}" width="100%" height="600" frameborder="0" sandbox="allow-scripts"></iframe>`;

  return {
    tokenId,
    token,
    embedCode,
    expiresAt,
  };
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
