interface SpecData {
  id: string;
  name: string;
  purpose: string;
  description?: string;
  model: string;
  source_simulation_id?: string;
}

interface TaskData {
  task_description: string;
  sequence_order: number;
  assignment: string;
  source_role?: string;
}

interface ToolData {
  tool_name: string;
  server_name: string;
  description?: string;
}

interface GuardrailData {
  guardrail_type: string;
  condition: string;
  action: string;
  priority: number;
}

interface CriterionData {
  metric_name: string;
  target_value: string;
  measurement_method?: string;
}

/**
 * Generate a full Claude Agent SDK Python project from a spec.
 * Returns a map of relative file paths to file contents.
 */
export function generateScaffold(
  spec: SpecData,
  tasks: TaskData[],
  tools: ToolData[],
  guardrails: GuardrailData[],
  criteria: CriterionData[],
  systemPrompt: string,
): Record<string, string> {
  const slug = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
  const files: Record<string, string> = {};

  // pyproject.toml
  files['pyproject.toml'] = `[project]
name = "${slug}"
version = "0.1.0"
description = "${spec.purpose.replace(/"/g, '\\"')}"
requires-python = ">=3.10"
dependencies = [
    "claude-agent-sdk>=0.1.19",
]

[project.scripts]
run-agent = "src.agent:main"
`;

  // CLAUDE.md — full spec context for Claude Code
  const toolList = tools.map((t) => `- \`${t.tool_name}\` (${t.server_name})${t.description ? ': ' + t.description : ''}`).join('\n');
  const taskList = tasks.map((t) => `${t.sequence_order}. [${t.assignment.toUpperCase()}] ${t.task_description}${t.source_role ? ' (from: ' + t.source_role + ')' : ''}`).join('\n');
  const guardrailList = guardrails.map((g) => `- [${g.guardrail_type.toUpperCase()}] ${g.condition} → ${g.action}`).join('\n');
  const criteriaList = criteria.map((c) => `- **${c.metric_name}**: ${c.target_value}`).join('\n');

  files['CLAUDE.md'] = `# ${spec.name}

## Purpose
${spec.purpose}

${spec.description ? `## Description\n${spec.description}\n` : ''}
## Tasks
${taskList}

## Tools
${toolList}

## Guardrails
${guardrailList}

## Success Criteria
${criteriaList}

## Source
${spec.source_simulation_id ? `Generated from WorkVine simulation: ${spec.source_simulation_id}` : 'Manually created'}
Spec ID: ${spec.id}
`;

  // Build MCP server configs for agent.py
  const uniqueServers = [...new Set(tools.map((t) => t.server_name))];
  const mcpServerEntries = uniqueServers.map((s) => {
    return `        "${s}": {
            "type": "stdio",
            "command": "bash",
            "args": [
                str(IVY_ROOT / "scripts" / "run-mcp.sh"),
                str(IVY_ROOT / "mcp-servers" / "${s}" / "src" / "index.ts"),
            ],
        }`;
  }).join(',\n');

  // Build guardrail hook entries
  const escalationGuardrails = guardrails.filter((g) => g.guardrail_type === 'escalation');
  const constraintGuardrails = guardrails.filter((g) => g.guardrail_type === 'constraint');

  // src/__init__.py
  files['src/__init__.py'] = '';

  // src/agent.py
  files['src/agent.py'] = `"""
${spec.name} — Claude Agent SDK Agent

Auto-generated by WorkVine Agent Builder.
"""
import asyncio
from pathlib import Path

from claude_agent_sdk import query, ClaudeAgentOptions

# Path to Ivy root (adjust if agent is deployed elsewhere)
IVY_ROOT = Path.home() / "Desktop" / "Ivy"

SYSTEM_PROMPT = """
${systemPrompt.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"')}
"""

OPTIONS = ClaudeAgentOptions(
    model="${spec.model}",
    system_prompt=SYSTEM_PROMPT,
    mcp_servers={
${mcpServerEntries}
    },
    permission_mode="bypassPermissions",
    max_turns=50,
)


async def run(task: str) -> None:
    """Run the agent with a specific task."""
    async for message in query(prompt=task, options=OPTIONS):
        if hasattr(message, "content"):
            for block in message.content:
                if hasattr(block, "text"):
                    print(block.text)


def main() -> None:
    """CLI entry point."""
    import sys
    task = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "${spec.purpose}"
    asyncio.run(run(task))


if __name__ == "__main__":
    main()
`;

  // src/guardrails.py
  const guardrailChecks = escalationGuardrails.map((g, i) => `
def check_escalation_${i}(tool_input: dict, tool_name: str) -> dict | None:
    """
    Condition: ${g.condition}
    Action: ${g.action}
    """
    # TODO: Implement condition check logic
    # Return a deny dict to block, or None to allow
    # Example:
    # if requires_ethical_review(tool_input):
    #     return {
    #         "hookSpecificOutput": {
    #             "hookEventName": "PreToolUse",
    #             "permissionDecision": "deny",
    #             "permissionDecisionReason": "${g.action.replace(/"/g, '\\"')}",
    #         }
    #     }
    return None
`).join('\n');

  const constraintChecks = constraintGuardrails.map((g, i) => `
def check_constraint_${i}(tool_input: dict, tool_name: str) -> dict | None:
    """
    Condition: ${g.condition}
    Action: ${g.action}
    """
    # TODO: Implement constraint check logic
    return None
`).join('\n');

  files['src/guardrails.py'] = `"""
Guardrail hooks for ${spec.name}.

These functions are called before/after tool use to enforce safety rules.
Implement the TODO sections with your specific business logic.
"""
${guardrailChecks}
${constraintChecks}

# Aggregate all checks for easy import
ESCALATION_CHECKS = [${escalationGuardrails.map((_, i) => `check_escalation_${i}`).join(', ')}]
CONSTRAINT_CHECKS = [${constraintGuardrails.map((_, i) => `check_constraint_${i}`).join(', ')}]
`;

  // src/tools.py
  files['src/tools.py'] = `"""
Custom tool definitions for ${spec.name}.

Add any agent-specific tools here that aren't available as MCP servers.
Uses the Claude Agent SDK @tool decorator pattern.
"""
from claude_agent_sdk import tool, create_sdk_mcp_server

# Example custom tool:
# @tool("my_tool", "Description of what it does", {"param": str})
# async def my_tool(args):
#     result = do_something(args["param"])
#     return {"content": [{"type": "text", "text": str(result)}]}

# Bundle custom tools into an MCP server:
# custom_server = create_sdk_mcp_server(name="custom-tools", tools=[my_tool])
`;

  // tests/test_agent.py
  files['tests/test_agent.py'] = `"""
Smoke tests for ${spec.name}.
"""
import pytest


def test_system_prompt_not_empty():
    from src.agent import SYSTEM_PROMPT
    assert len(SYSTEM_PROMPT.strip()) > 100


def test_options_has_mcp_servers():
    from src.agent import OPTIONS
    assert OPTIONS.mcp_servers is not None
    assert len(OPTIONS.mcp_servers) >= 1


def test_guardrail_checks_exist():
    from src.guardrails import ESCALATION_CHECKS, CONSTRAINT_CHECKS
    assert isinstance(ESCALATION_CHECKS, list)
    assert isinstance(CONSTRAINT_CHECKS, list)
`;

  // README.md
  files['README.md'] = `# ${spec.name}

${spec.purpose}

## Quick Start

\`\`\`bash
# Install dependencies
pip install -e .

# Run the agent
python -m src.agent "Your task here"

# Or use the CLI entry point
run-agent "Your task here"
\`\`\`

## Architecture

This agent uses the **Claude Agent SDK** with MCP server tools from the Ivy platform.

### MCP Servers
${uniqueServers.map((s) => `- \`${s}\``).join('\n')}

### Guardrails
${guardrails.length} guardrail rules are defined in \`src/guardrails.py\`.
${escalationGuardrails.length > 0 ? `- ${escalationGuardrails.length} escalation rules (stop and involve human)` : ''}
${constraintGuardrails.length > 0 ? `- ${constraintGuardrails.length} constraint rules (limit agent behavior)` : ''}

### Success Criteria
${criteria.map((c) => `- **${c.metric_name}**: ${c.target_value}`).join('\n')}

## Testing

\`\`\`bash
pytest tests/
\`\`\`

---
*Generated by WorkVine Agent Builder from spec \`${spec.id}\`*
`;

  return files;
}
